#!/bin/bash

#SBATCH -p gpu3     # 在 gpu1 分区运行（不写默认为 cpu1）
#SBATCH -N 1          # 只在一个节点上运行任务
#SBATCH -c 3          # 申请 CPU 核心：1个
#SBATCH --mem 20G     # 申请内存：500 MB
#SBATCH --gres gpu:1  # 分配1个GPU（纯 CPU 任务不用写）
# #SBATCH --nodelist wmc-slave-g12
# #SBATCH -o log/%j-train-30.out

date
echo "job begin"

# python resample.py;
# python preprocess_flist_config.py;
# python preprocess_hubert_f0.py;
# python train.py -c configs/config.json -m 44k


# Example
# python inference_main.py -m "logs/44k/G_20000.pth" -c "configs/config.json" -s "opencpop" -n "chunk_18.wav" -t 0

# ### inference
for i in {0..31}
do
#    python inference_main.py -m "logs_from_zero/44k/G_20000.pth" -c "configs/config.json" -s "opencpop" -n "chunk_${i}.wav" -t 0
   # python inference_main.py -m "logs/44k/G_49600.pth" -c "configs/config.json" -s "opencpop" -n "chunk_${i}.wav" -t 0
   # python inference_main.py -m "logs/44k/G_60000.pth" -c "configs/config.json" -s "opencpop" -n "chunk_${i}.wav" -t 0
   # python inference_main.py -m "logs/44k/G_66400.pth" -c "configs/config.json" -s "opencpop" -n "chunk_${i}.wav" -t 0
   # python inference_main.py -m "pre_train-model/so-vits-svc-arknights-astesi-aurora/G_599200.pth" -c "configs/config.json" -s "opencpop" -n "chunk_${i}.wav" -t 0
   # python inference_main.py -m "pre_train-model/lqlkluso-vits-svc-4.0-danxiao/G_10600.pth" -c "configs/config.json" -s "opencpop" -n "chunk_${i}.wav" -t 0
   python inference_main.py -m "logs/44k_from_danxiao/G_60000.pth" -c "configs/config.json" -s "opencpop" -n "chunk_${i}.wav" -t 0
done


echo "job end"
date